version: '3'

services:
  api:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=fastApiTest.py
      - FLASK_DEBUG=1
      - 'RUN=uvicorn fastApiTest:app --reload'
    command: uvicorn fastApiTest:app --reload
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
