# This is a basic workflow to help you get started with Actions

name: Update Cambodia ID Poor

on:
  schedule:
    # Run every month
    - cron: '0 0 0 1 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ROUNDS_COUNT: 6

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: https://mop.idpoor.gov.kh/api/analytics/public/units/KH
          configuration: '{ "method": "GET" }'

      # Run alert worker
      - run: cd alerting
      - run: yarn
      - run: ts-node src/alert-worker.ts
